version: '3.8'

services:
  phone-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phone-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - phone-network
    volumes:
      # 如果需要持久化数据，可以挂载数据目录
      # - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: phone-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - phone-app
    restart: unless-stopped
    networks:
      - phone-network

networks:
  phone-network:
    driver: bridge

volumes:
  logs: 