services:
  phone-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phone-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    volumes:
      # 持久化数据目录 - 包含聊天室JSON文件和SQLite数据库
      - ./data:/app/data
      # 可选：持久化日志文件
      - ./logs:/app/logs
    # 添加用户映射，确保权限正确
    user: "1000:1000"
    networks:
      - phone-network

networks:
  phone-network:
    driver: bridge 