version: '3.8'

services:
  phone-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phone-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - phone-network

networks:
  phone-network:
    driver: bridge 