'use client';

import React, { useState } from 'react';
import { DiscoverSettings } from '../../types/discover';
import { autoGenerationService } from './utils/autoGenerationService';
import { useI18n } from '../i18n/I18nProvider';
import './DiscoverSettingsPanel.css';

interface DiscoverSettingsPanelProps {
  settings: DiscoverSettings;
  onSave: (settings: DiscoverSettings) => void;
  onCancel: () => void;
}

export default function DiscoverSettingsPanel({ 
  settings, 
  onSave, 
  onCancel 
}: DiscoverSettingsPanelProps) {
  const { t } = useI18n();
  
  // 确保间隔时间不小于5分钟
  const normalizedSettings = {
    ...settings,
    autoGenerateInterval: Math.max(settings.autoGenerateInterval, 5)
  };
  
  const [localSettings, setLocalSettings] = useState<DiscoverSettings>(normalizedSettings);
  const [isSaving, setIsSaving] = useState(false);

  const handleSave = async () => {
    setIsSaving(true);
    try {
      await onSave(localSettings);
      
      // 更新自动生成服务设置
      await autoGenerationService.updateSettings(localSettings);
      
      console.log('✅ ' + t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.logs.settingsSaved', '设置已保存并更新自动生成服务'));
    } catch (error) {
      console.error('Failed to save settings:', error);
    } finally {
      setIsSaving(false);
    }
  };

  const updateSetting = <K extends keyof DiscoverSettings>(
    key: K, 
    value: DiscoverSettings[K]
  ) => {
    console.log('🔧 ' + t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.logs.settingUpdated', '设置更新: {{key}} = {{value}}').replace('{{key}}', key).replace('{{value}}', String(value)));
    setLocalSettings(prev => ({ ...prev, [key]: value }));
  };

  return (
    <div className="modal-overlay" onClick={(e) => e.target === e.currentTarget && onCancel()}>
      <div className="api-settings-modal">
        <div className="modal-header">
          <h2>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.title', '动态设置')}</h2>
          <button className="close-btn" onClick={onCancel}>×</button>
        </div>
        
        <div className="modal-body">
          {/* 当前状态显示 */}
          <div className="tip-box">
            <div className="status-item">
              <span>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.status.current', '当前状态:')}</span>
              <span className={`status-value ${settings.autoGeneratePosts ? 'active' : 'inactive'}`}>
                {settings.autoGeneratePosts ? t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.status.autoGenerateEnabled', '✅ 自动生成动态已开启') : t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.status.autoGenerateDisabled', '❌ 自动生成动态已关闭')}
              </span>
            </div>
            <div className="status-item">
              <span>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.status.comments', '评论状态:')}</span>
              <span className={`status-value ${settings.allowAiComments ? 'active' : 'inactive'}`}>
                {settings.allowAiComments ? t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.status.aiCommentsEnabled', '✅ AI评论已开启') : t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.status.aiCommentsDisabled', '❌ AI评论已关闭')}
              </span>
            </div>
          </div>

          {/* AI自动生成设置 */}
          <div className="form-group">
            <label htmlFor="auto-generate-posts">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.autoGenerate.label', '自动生成AI动态')}</label>
            <div className="toggle-group">
              <div className="toggle-label">
                <span>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.autoGenerate.description', 'AI角色会自动发布动态')}</span>
              </div>
              <input
                type="checkbox"
                id="auto-generate-posts"
                checked={localSettings.autoGeneratePosts}
                onChange={(e) => updateSetting('autoGeneratePosts', e.target.checked)}
              />
            </div>
          </div>

          {localSettings.autoGeneratePosts && (
            <div className="form-group">
              <label htmlFor="generate-interval">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.label', '生成间隔（分钟）')}</label>
              <select
                id="generate-interval"
                value={localSettings.autoGenerateInterval}
                onChange={(e) => updateSetting('autoGenerateInterval', parseInt(e.target.value))}
                className="select-input"
              >
                <option value={5}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.5min', '5分钟')}</option>
                <option value={10}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.10min', '10分钟')}</option>
                <option value={15}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.15min', '15分钟')}</option>
                <option value={30}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.30min', '30分钟')}</option>
                <option value={60}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.1hour', '1小时')}</option>
                <option value={120}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.2hours', '2小时')}</option>
                <option value={240}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.4hours', '4小时')}</option>
                <option value={480}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.8hours', '8小时')}</option>
                <option value={720}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.12hours', '12小时')}</option>
                <option value={1440}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.options.24hours', '24小时')}</option>
              </select>
              <small className="field-hint">
                {t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.generateInterval.hint', 'AI动态生成的时间间隔，最少5分钟以避免与慢速模型冲突')}
              </small>
            </div>
          )}

          <div className="form-group">
            <label htmlFor="max-posts-per-day">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.maxPostsPerDay.label', '每日最大动态数')}</label>
            <input
              type="number"
              id="max-posts-per-day"
              min="1"
              max="50"
              value={localSettings.maxPostsPerDay}
              onChange={(e) => updateSetting('maxPostsPerDay', parseInt(e.target.value) || 10)}
              className="number-input"
            />
            <small className="field-hint">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.maxPostsPerDay.hint', '限制每日发布的动态数量')}</small>
          </div>

          <hr className="divider" />

          {/* AI互动设置 */}
          <div className="form-group">
            <label htmlFor="allow-ai-comments">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.allowAiComments.label', '允许AI评论')}</label>
            <div className="toggle-group">
              <div className="toggle-label">
                <span>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.allowAiComments.description', 'AI角色可以对动态进行评论')}</span>
              </div>
              <input
                type="checkbox"
                id="allow-ai-comments"
                checked={localSettings.allowAiComments}
                onChange={(e) => updateSetting('allowAiComments', e.target.checked)}
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="allow-ai-likes">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.allowAiLikes.label', '允许AI点赞')}</label>
            <div className="toggle-group">
              <div className="toggle-label">
                <span>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.allowAiLikes.description', 'AI角色可以对动态进行点赞')}</span>
              </div>
              <input
                type="checkbox"
                id="allow-ai-likes"
                checked={localSettings.allowAiLikes}
                onChange={(e) => updateSetting('allowAiLikes', e.target.checked)}
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="prevent-ai-cross-comments">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.preventAiCrossComments.label', '禁止AI角色互相评论')}</label>
            <div className="toggle-group">
              <div className="toggle-label">
                <span>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.preventAiCrossComments.description', '开启后，AI角色只能评论用户动态，不能互相评论')}</span>
              </div>
              <input
                type="checkbox"
                id="prevent-ai-cross-comments"
                checked={localSettings.preventAiCrossComments}
                onChange={(e) => updateSetting('preventAiCrossComments', e.target.checked)}
              />
            </div>
            <small className="field-hint">
              {t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.preventAiCrossComments.hint', '开启此选项后，AI角色将只对用户发布的动态进行评论，不会对其他AI角色的动态进行评论')}
            </small>
          </div>

          <hr className="divider" />

          {/* 隐私设置 */}
          <div className="form-group">
            <label htmlFor="privacy-level">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.privacyLevel.label', '默认隐私级别')}</label>
            <select
              id="privacy-level"
              value={localSettings.privacyLevel}
              onChange={(e) => updateSetting('privacyLevel', e.target.value as 'public' | 'friends' | 'private')}
            >
              <option value="public">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.privacyLevel.options.public', '公开')}</option>
              <option value="friends">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.privacyLevel.options.friends', '仅好友')}</option>
              <option value="private">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.privacyLevel.options.private', '私密')}</option>
            </select>
            <small className="field-hint">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.privacyLevel.hint', '新动态的默认可见范围')}</small>
          </div>

          <div className="form-group">
            <label htmlFor="notify-on-new-posts">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.notifyOnNewPosts.label', '新动态通知')}</label>
            <div className="toggle-group">
              <div className="toggle-label">
                <span>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.notifyOnNewPosts.description', '收到新动态时显示通知')}</span>
              </div>
              <input
                type="checkbox"
                id="notify-on-new-posts"
                checked={localSettings.notifyOnNewPosts}
                onChange={(e) => updateSetting('notifyOnNewPosts', e.target.checked)}
              />
            </div>
          </div>

          <hr className="divider" />

          {/* 主题设置 */}
          <div className="form-group">
            <label htmlFor="theme">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.theme.label', '动态主题')}</label>
            <select
              id="theme"
              value={localSettings.theme}
              onChange={(e) => updateSetting('theme', e.target.value)}
            >
              <option value="default">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.theme.options.default', '默认')}</option>
              <option value="dark">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.theme.options.dark', '深色')}</option>
              <option value="light">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.theme.options.light', '浅色')}</option>
              <option value="auto">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.theme.options.auto', '跟随系统')}</option>
            </select>
            <small className="field-hint">{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.theme.hint', '动态页面的显示主题')}</small>
          </div>
        </div>

        <div className="modal-footer">
          <button className="cancel-btn" onClick={onCancel} disabled={isSaving}>{t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.buttons.cancel', '取消')}</button>
          <button className="save-btn" onClick={handleSave} disabled={isSaving}>
            {isSaving ? t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.buttons.saving', '保存中...') : t('QQ.ChatInterface.Discover.DiscoverSettingsPanel.buttons.save', '保存配置')}
          </button>
        </div>
      </div>
    </div>
  );
} 